### ISSUE TITLE
Problem with S3DownloadObjectOperation (signature incorrect).

### ISSUE THREAD

**Issue by execomrt** [olg/objc-s3#1] opened 2011-09-30 02:56 UTC
I'm using objc-s3 because this is the only code for OSX/Objective C that handle Amazon S3.
The code works fine for uploading, but not downloading.
Using
- (BOOL) downloadFromBucket:(NSString_)theBucket key:(NSString_)key saveTo:(NSString*)path
  {
  
  S3Bucket *bucket = [[S3Bucket alloc] initWithName: theBucket];
  S3Object *objectToDownload = [[S3Object alloc] initWithBucket:bucket 
                                                       key:key 
                                       userDefinedMetadata:nil 
                                                  metadata:nil 
                                            dataSourceInfo:nil];
  
  S3DownloadObjectOperation\* op = [[S3DownloadObjectOperation alloc] 
                                   initWithConnectionInfo:[self connectionInfo] 
                                   object: objectToDownload
                                   saveTo:path
                                   ];
  
  [_queue addToCurrentOperations:op];
  [op release];
  return TRUE;

}

This is generating an error. It seems that the code is not generating the correct signature. Can you fix the problem ?

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><StringToSignBytes>47 45 54 0a 0a 0a 46 72 69 2c 20 33 30 20 53 65 70 20 32 30 31 ?? 20 30 32 ?? 33 39 3a 32 31 20 2b ?? 30 30 30 0a 2f 67 6c 76 69 65 77 2f 65 78 74 65 6e 73 69 6f 6e 73 2e 7a 69 70</StringToSignBytes><RequestId>9E7EC5195AED6873</RequestId><HostId>BENzToJUiC9Keunx1NYSCSJMG9fHTqx/CyRdeJ/rScvr+VrSh99y8u+jqTTThdNZ</HostId><SignatureProvided>???????????????????</SignatureProvided><StringToSign>GET

Fri, 30 Sep 2011 02:39:21 +0000
/glview/extensions.zip</StringToSign><AWSAccessKeyId>???????????????????</AWSAccessKeyId></Error>

PS: I've obfucated some bits

**Comment by gpoul** [comment] 2011-09-30 06:48
You used the code in the experimental branch, right? Not sure whether michael's core code redesign might be involved in this problem.

@mledford would you be able to look at that?

**Comment by mledford** [comment] 2011-09-30 16:26
@execomrt Can you give some context under what circumstances this is occurring. Some questions I have follows:

1) Which branch are you working off of? I know the experimental works. It's been so long I don't remember much about the state of stable. But given its name I would expect it to work as well.
2) What region is your bucket hosted in?
3) Is your bucket virtually hosted?

Given that you say you can upload an object I'm going to make the assumption that your code is setup correctly.

**Comment by mledford** [comment] 2011-09-30 16:38
As a side note this isn't the only Obj-C code to access Amazon S3. I'm not trying to discourage your usage of objc-s3 I just wanted to make you aware that there is other code that might be more well tended.

Some examples are:

1) AWS SDK for iOS - http://aws.amazon.com/sdkforios/
2) ConnectionKit - https://github.com/karelia/ConnectionKit
3) ASIHTTPRequest - http://allseeing-i.com/ASIHTTPRequest/S3

**Comment by execomrt** [comment] 2011-09-30 18:46
Hello;

I've used the latest version. As I said, it works for uploading, but
not download. I think the problem comes from the signature code.
Anyway, I've hacked AWS for iOS for MacOSX (by removing iOS specific
code and header) and it worked.

Thanks again, but you should have a look in your sign code.

Cheers;

On Fri, 30 Sep 2011 09:38:09 -0700, Michael Ledford
reply@reply.github.com
wrote:

> As a side note this isn't the only Obj-C code to access Amazon S3.
> I'm not trying to discourage your usage of objc-s3 I just wanted to
> make you aware that there is other code that might be more well
> tended.
> 
> Some examples are:
> 
> 1) AWS SDK for iOS - http://aws.amazon.com/sdkforios/
> 2) ConnectionKit - https://github.com/karelia/ConnectionKit
> 3) ASIHTTPRequest - http://allseeing-i.com/ASIHTTPRequest/S3

**Comment by mledford** [comment] 2011-09-30 18:50
@execomrt Glad that you found something that works for you. I believe the code works. The S3Browser application uses the same objects that you are using and I can upload and download fine. But I need some help from you in order to find the possible bug that you have pointed out. Can you answer the questions I asked above?

**Comment by mledford** [comment] 2011-11-22 03:17
Closing due to the reporter not giving enough information to reproduce the claim.

**Closed as completed by mledford** 2011-11-22 03:17 UTC
